/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Dao.AutomataPilaDAO;
import Dao.IAutomataPilaDAO;
import Modelo.AutomataPila;
import Utils.ConversorAutomata;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Modelo.Estado;
import excepcion.AutomataPilaExcepcion;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario externo
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    //JFileChooser seleccionar = new JFileChooser();
    //FileImageInputStream entrada;
    //FileImageInputStream salida;
    File archivo;
    AutomataPila automata;
    IAutomataPilaDAO automataDAO;
    public static ArrayList<Estado> estados;
    public static String estadoSeleccionado;
    

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_estadoInicial = new javax.swing.JTextField();
        txt_simbolosDeEntrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_confInicial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_simbolosEnLaPila = new javax.swing.JTextField();
        cargarArchivo = new javax.swing.JButton();
        cboEstados = new javax.swing.JComboBox<>();
        btnVerModificarEstado = new javax.swing.JButton();
        btnAñadirEstado = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboSimEntrada = new javax.swing.JComboBox<>();
        btnAgregarSimEntrada = new javax.swing.JButton();
        btnEditarSimEntrada = new javax.swing.JButton();
        btnEliminarSimEntrada = new javax.swing.JButton();
        txtSimboloEntrada = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Simbolos de entrada:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        jPanel1.add(txt_estadoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 170, 28));

        txt_simbolosDeEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_simbolosDeEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_simbolosDeEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Simbolos en la Pila:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Configuración inicial de la Pila:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Estados:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));
        jPanel1.add(txt_confInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 170, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Estado Inicial:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        txt_simbolosEnLaPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_simbolosEnLaPilaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_simbolosEnLaPila, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 170, 28));

        cargarArchivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cargarArchivo.setText("Cargar archivo");
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(cargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jPanel1.add(cboEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 100, 30));

        btnVerModificarEstado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVerModificarEstado.setForeground(new java.awt.Color(255, 255, 255));
        btnVerModificarEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu_show.png"))); // NOI18N
        btnVerModificarEstado.setToolTipText("Ver o Editar");
        btnVerModificarEstado.setBorder(null);
        btnVerModificarEstado.setBorderPainted(false);
        btnVerModificarEstado.setContentAreaFilled(false);
        btnVerModificarEstado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerModificarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerModificarEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerModificarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 30, 30));

        btnAñadirEstado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAñadirEstado.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadirEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_dark.png"))); // NOI18N
        btnAñadirEstado.setToolTipText("Añadir");
        btnAñadirEstado.setBorder(null);
        btnAñadirEstado.setBorderPainted(false);
        btnAñadirEstado.setContentAreaFilled(false);
        btnAñadirEstado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAñadirEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadirEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 30, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("autómata de pila o carguelos desde un archivo de texto");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("A continuación ingrese cada uno de los datos de su ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(cboSimEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 30));

        btnAgregarSimEntrada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregarSimEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarSimEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_dark.png"))); // NOI18N
        btnAgregarSimEntrada.setToolTipText("Agregar");
        btnAgregarSimEntrada.setBorder(null);
        btnAgregarSimEntrada.setBorderPainted(false);
        btnAgregarSimEntrada.setContentAreaFilled(false);
        btnAgregarSimEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarSimEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSimEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarSimEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 30, 30));

        btnEditarSimEntrada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditarSimEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarSimEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditarSimEntrada.setToolTipText("Modificar");
        btnEditarSimEntrada.setBorder(null);
        btnEditarSimEntrada.setBorderPainted(false);
        btnEditarSimEntrada.setContentAreaFilled(false);
        btnEditarSimEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarSimEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSimEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarSimEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 30, 30));

        btnEliminarSimEntrada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminarSimEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarSimEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/showdeleted.png"))); // NOI18N
        btnEliminarSimEntrada.setToolTipText("Eliminar");
        btnEliminarSimEntrada.setBorder(null);
        btnEliminarSimEntrada.setBorderPainted(false);
        btnEliminarSimEntrada.setContentAreaFilled(false);
        btnEliminarSimEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarSimEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSimEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarSimEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 30, 30));
        jPanel1.add(txtSimboloEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 410, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Hilera:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 210, -1));

        jButton2.setText("Evaluar");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));
        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 30, 310));

        jLabel7.setText("La hilera ingresada es : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jTextField2.setText("válida/inválida");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 300, 530));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Autómatas de pila");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed
        JFileChooser abrir;       
        abrir = new JFileChooser();
        abrir.showOpenDialog(this);
        archivo = abrir.getSelectedFile();
        if(archivo != null){
        try {
            ConversorAutomata conversor = new ConversorAutomata();
            automata = conversor.convertir(archivo);
            llenarFormulario();    
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Su archivo no se ha leido correctamente", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cargarArchivoActionPerformed

    private void txt_simbolosDeEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_simbolosDeEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_simbolosDeEntradaActionPerformed

    private void txt_simbolosEnLaPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_simbolosEnLaPilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_simbolosEnLaPilaActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnAñadirEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadirEstadoActionPerformed

    private void btnVerModificarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerModificarEstadoActionPerformed
        estadoSeleccionado = cboEstados.getSelectedItem().toString();
        VistaEditarEstado vee = new VistaEditarEstado();
        vee.setVisible(true);
        
    }//GEN-LAST:event_btnVerModificarEstadoActionPerformed

    private void btnAgregarSimEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSimEntradaActionPerformed
        automataDAO = new AutomataPilaDAO();
        try {
            automata = automataDAO.agregarSimboloEntrada(automata, txtSimboloEntrada.getText());
            //llenarFormulario();
        } catch (AutomataPilaExcepcion ex) {
            JOptionPane.showMessageDialog(null, "Error al agregar simbolo de entrada: "+ ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarSimEntradaActionPerformed

    private void btnEditarSimEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSimEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSimEntradaActionPerformed

    private void btnEliminarSimEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSimEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarSimEntradaActionPerformed

    private void llenarFormulario(){
        String simbolos = "";
        for(String i : automata.getSimbolosEntrada()){
            simbolos += i + " ";
        }
        txt_simbolosDeEntrada.setText(simbolos);
        simbolos = "";
        for(String i : automata.getSimbolosPila()){
            simbolos += i + " ";
        }
        txt_simbolosEnLaPila.setText(simbolos);
        simbolos = "";
        for(String i : automata.getConfiguracionInicial()){
            simbolos += i + " ";
        }
        txt_confInicial.setText(simbolos);
        txt_estadoInicial.setText(automata.getEstadoInicial());

        estados = automata.getEstados();
        for(Estado e : estados){
            cboEstados.addItem(e.getNombre());
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarSimEntrada;
    private javax.swing.JButton btnAñadirEstado;
    private javax.swing.JButton btnEditarSimEntrada;
    private javax.swing.JButton btnEliminarSimEntrada;
    private javax.swing.JButton btnVerModificarEstado;
    private javax.swing.JButton cargarArchivo;
    private javax.swing.JComboBox<String> cboEstados;
    private javax.swing.JComboBox<String> cboSimEntrada;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtSimboloEntrada;
    private javax.swing.JTextField txt_confInicial;
    private javax.swing.JTextField txt_estadoInicial;
    private javax.swing.JTextField txt_simbolosDeEntrada;
    private javax.swing.JTextField txt_simbolosEnLaPila;
    // End of variables declaration//GEN-END:variables
}
